FROM maven:3.9.9-eclipse-temurin-21 AS build
WORKDIR /app
COPY pom.xml ./
RUN mvn dependency:go-offline -B
COPY . ./
RUN mvn clean package -DskipTests
FROM openjdk:21-slim
WORKDIR /app
COPY --from=build /app/target/RateLimitingApp-1.0-SNAPSHOT.jar ratelimitingapp.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "ratelimitingapp.jar"]